---
- name: Test oracle-db xe from static
  hosts: all
  vars:
    oracle_version: xe
    transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-install"
    oracle_images:
      - linux.x64_11gR2_xe.zip
  roles:
    - role: ansible-role-oracle-db
  become: True
