---

- name: "Install Oracle RDBMS"
  become_user: "{{ oracledb.user }}"
  shell: >
      {{ oracledb.install_directory }}/database/runInstaller -silent
      -waitforcompletion -ignorePrereq -responseFile
      {{ oracledb.install_directory }}/{{ oracledb.rsp_file }}
  register: rdbms_install
  tags:
    - skip_ansible_lint
  failed_when: "(rdbms_install.stdout_lines is undefined) or
                ('Successfully Setup Software.' not in rdbms_install.stdout_lines)"
  become: True

- name: "Start scripts after install"
  shell: "{{ inventory_directory }}/orainstRoot.sh"
  tags:
    - skip_ansible_lint
  become: True

- name: "Start root.sh script"
  shell: "{{ oracledb.oracle_home }}/root.sh"
  tags:
    - skip_ansible_lint
  become: True

- name: "Create rsp file for oracle"
  template:
    src: "pwd.rsp.j2"
    dest: "{{ oracledb.install_directory }}/{{ oracledb.pwd_file }}"
    owner: "{{ oracledb.user }}"
    group: "{{ oracledb.install_group }}"
  become: True

- name: "Create db"
  become_user: "{{ oracledb.user }}"
  shell: >
      {{ oracledb.oracle_home }}/cfgtoollogs/configToolAllCommands
      RESPONSE_FILE={{ oracledb.install_directory }}/{{ oracledb.pwd_file }}
  register: db_install
  tags:
    - skip_ansible_lint
  failed_when: "(db_install.stdout_lines is undefined) or
                ('perform - mode finished for action: configure' not in db_install.stdout_lines)"
  become: True

- name: "Change oratab"
  lineinfile:
    dest: /etc/oratab
    state: present
    regexp: "{{ sid }}"
    line: "{{ sid }}:{{ oracledb.oracle_home }}:Y"
  become: True

- name: "Create environment variables"
  template:
    src: "env.oracledb.sysconfig.j2"
    dest: "/etc/sysconfig/env.oracledb"
  become: True

- name: "Create systemd Oracle databases service for Centos 7"
  template:
    src: oracledb.systemd.j2
    dest: "/etc/systemd/system/oracledb.service"
  when: ansible_distribution_major_version == '7'
  become: True

- name: "Create systemd Oracle databases service for Centos 6"
  template:
    src: oracledb.sysv.j2
    dest: "/etc/init.d/oracledb"
    mode: "0755"
  when: ansible_distribution_major_version == '6'
  become: True

- name: "Copy template for user creation for oracle"
  template:
    src: "user.sql.j2"
    dest: "{{ oracledb.oracle_home }}/user.sql"
    owner: "{{ oracledb.user }}"
    group: "{{ oracledb.install_group }}"
  become: True

- name: "Execute sql query for Oracle user, tablespace creation"
  become_user: "{{ oracledb.user }}"
  shell: >
      source /home/{{ oracledb.user }}/.bashrc && {{ oracledb.oracle_home }}/bin/sqlplus /
      as sysdba @{{ oracledb.oracle_home }}/user.sql
  tags:
    - skip_ansible_lint
  become: True

- name: "Stop the Oracle listener"
  become_user: "{{ oracledb.user }}"
  shell: >
    {{ oracledb.oracle_home }}/bin/lsnrctl stop
  tags:
    - skip_ansible_lint
  become: True

- name: "Setup database port"
  replace:
    path: "{{ oracledb.oracle_home }}/network/admin/{{ item }}"
    regexp: "PORT = \\d+"
    replace: "PORT = {{ db_port }}"
    backup: True
  loop:
    - "listener.ora"
    - "tnsnames.ora"
  become: True

- name: "Start the Oracle listener"
  become_user: "{{ oracledb.user }}"
  shell: >
    source /home/{{ oracledb.user }}/.bashrc && {{ oracledb.oracle_home }}/bin/lsnrctl start
  tags:
    - skip_ansible_lint
  become: True

- name: "Copy template for port changing"
  template:
    src: "change_port.sql.j2"
    dest: "{{ oracledb.oracle_home }}/change_port.sql"
    owner: "{{ oracledb.user }}"
    group: "{{ oracledb.install_group }}"
  become: True

- name: "Execute sql query for Oracle user, tablespace creation"
  become_user: "{{ oracledb.user }}"
  shell: >
    source /home/{{ oracledb.user }}/.bashrc && {{ oracledb.oracle_home }}/bin/sqlplus /
    as sysdba @{{ oracledb.oracle_home }}/change_port.sql
  tags:
    - skip_ansible_lint
  become: True
