---
- name: Prepare Ubuntu / Debian
  hosts: debian_family
  gather_facts: False
  tasks:

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt install -y python-minimal)
      become: True
      changed_when: False
      register: update_result
      retries: 10
      delay: 5
      until: update_result.rc == 0

- name: Prepare RHEL
  hosts: rhel_family
  gather_facts: False
  vars:
    ssh_port: 22
  tasks:
  
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (yum install -y python2 python-simplejson)
      become: True
      changed_when: False
      register: update_result
      retries: 10
      delay: 5
      until: update_result.rc == 0

    - name: Wait for server to restart
      wait_for_connection:
        delay: 60
        timeout: 300

    - name: Wait for SSH
      wait_for:
        port: '{{ ssh_port }}'
        host: '{{ item.address }}'
        search_regex: SSH
        delay: 2
        timeout: 320
      loop: "{{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"
